### ISSUE TITLE
Documentation on docs.rs fails to build and GitHub workflows that involve building do not work

### ISSUE THREAD

**Issue by 0xdea** [binarly-io/idalib#9]
I noticed that documentation for idalib and idalib-sys currently [fails to build](https://docs.rs/crate/idalib-sys/latest) on docs.rs. This in caused by the following [error](https://docs.rs/crate/idalib-sys/0.1.1+9.0.240930/builds/1449438):

```
[INFO] [stderr]   thread 'main' panicked at build.rs:34:56:
[INFO] [stderr]   IDASDKDIR should be set: NotPresent
```

Obviously, the IDA SDK is missing. Other than providing the IDA SDK in the package (which I believe cannot be done because of its license), do you know if there's a way to build only the documentation without having to build and link any problematic code? It looks like [it should be possible](https://docs.rs/about/builds), but I couldn't find a reliable way to do it.

A related problem is that GitHub workflows such as [this one](https://github.com/0xdea/rhabdomancer/blob/master/.github/workflows/rust.yml) do not work because in order to run `cargo clippy` you must be able to build the package. Any idea on how to fix this?

**Comment by xorpse** [comment]
For documentation, I think the easiest route will be for us to build it ourselves (offline or via GitHub Actions) and deploy using GitHub Pages. If we set the documentation key in `Cargo.toml` appropriately, crates.io will link to the right place. I agree that there should be a way to acheive what we want via docs.rs, but it might be more trouble than it's worth.

For workflows, it should be straightforward to implement something similar to what @yeggor has done with our efiXplorer (https://github.com/binarly-io/efiXplorer/blob/dca0d07740853462f7a71f75b3ed710280e4ec05/.github/workflows/ci-build.yml#L11), where we have the SDK hosted as a password protected/encrypted archive "somewhere" and downloaded/unpacked as a build step, then used as we would in a local build.

Since both of these issues will also affect downstream consumers of idalib, we should definitely provide some documentation/guidance.

**Comment by xorpse** [comment]
We've added workflows for build and documentation generation in https://github.com/binarly-io/idalib/commit/cf80fb27a09bfc0182a6a854811141a6ba378c18. It should be straightforward to adopt something similar in repositories for crates using idalib--it will just require adding appropriate `IDASDK90_{PASSWORD,URL}` secrets.
